Update golangci lint (#197)
* Use tenv linter replacement

The linter 'tenv' is deprecated (since v1.64.0) due to: Duplicate
feature in another linter. Replaced by usetesting.

* Remove superflous lint workflow comments

* Update golangci-lint version

Due to the following lint workflow failures

    Error: can't load config: the Go language version (go1.24) used to build
    golangci-lint is lower than the targeted Go version (1.25.0)
    Failed executing command with error: can't load config: the Go
    language version (go1.24) used to build golangci-lint is lower than
    the targeted Go version (1.25.0)

the linter is upgraded.

* Run golangci-lint migrate

* Run golangci-lint run --fix

* Address lint issues raised in new linter version

* Avoid parallel with t.Setenv