Update golangci-lint version
Due to the following lint workflow failures

    Error: can't load config: the Go language version (go1.24) used to build
    golangci-lint is lower than the targeted Go version (1.25.0)
    Failed executing command with error: can't load config: the Go
    language version (go1.24) used to build golangci-lint is lower than
    the targeted Go version (1.25.0)

the linter is upgraded.